#!/bin/bash
d=$1

if [ "$(hyprctl activewindow -j | jq -r '.floating')" = "false" ]; then
  hyprctl dispatch -q swapwindow "$d"
else
  w="0"
  h="0"
  case $d in
    l) w="-100" ;;
    r) w="100" ;;
    u) h="-50" ;;
    d) h="100" ;;
  esac
  hyprctl dispatch -q moveactive "$w" "$h"
fi
