#!/usr/bin/env /bin/bash

function minimized {
  WSID="${1}"

  hyprctl clients -j | \
    jq -r "map(select(.workspace.id == $WSID and .floating == true and (.tags | contains([\"modal*\"]) | not)))" | \
    jq "\"dispatch movetoworkspacesilent special:minimized$WSID,address:\" + (.[] | .address)" | \
    jq -sr 'join("; ")' | \
    xargs hyprctl -q --batch
}

function unminimized {
  WSID="$(hyprctl activeworkspace -j | jq -r '.id')"

  hyprctl clients -j | \
    jq -r "map(select(.workspace.name == \"special:minimized$WSID\"))" | \
    jq "\"dispatch movetoworkspacesilent $WSID,address:\" + (.[] | .address)" | \
    jq -sr 'join("; ")' | \
    xargs hyprctl -q --batch
}

function handle {
  if [[ ${1:0:14} == "activewindowv2" ]]; then
    JSON="$(hyprctl activewindow -j)"
    FLOATING="$(echo $JSON | jq -r '.floating')"

    if [[ "$FLOATING" == "false" ]] ; then
      WSID="$(echo $JSON | jq -r '.workspace.id')"
      minimized "$WSID"
    else
      unminimized
      FILE="/tmp/hyprlistener-$HYPRLAND_INSTANCE_SIGNATURE-$WSID.tmp"
      ADDR="$(head -1q $FILE 2>/dev/null)"
      rm -f $FILE

      if [[ $ADDR == 0x* ]] ; then
          hyprctl -q --batch "\
            dispatch focuswindow address:$ADDR ; \
            dispatch alterzorder top,address:$ADDR"
      else
          if [[ "$JSON" == "{}" || \
              "$(hyprctl activewindow -j | jq -r '.floating')" == "false" ]] ; then
              hyprctl -q dispatch cyclenext prev floating hist
          fi
          hyprctl -q dispatch alterzorder "top,address:$(hyprctl activewindow -j | jq -r ".address")"
      fi
    fi
  fi
}

SOCKET2_PATH="$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock"

nc -U "$SOCKET2_PATH" | while read -r line; do handle "$line"; done

