#!/usr/bin/env /bin/bash

function handle {
  if [[ ${1:0:14} == "activewindowv2" ]]; then
    JSON="$(hyprctl activewindow -j)"
    FLOATING="$(echo $JSON | jq -r '.floating')"

    if [[ "$FLOATING" == "false" ]] ; then
        WSID="$(echo $JSON | jq -r '.workspace.id')"

        while IFS= read -r CLIENT_JSON ; do
            if [[ "$(echo $CLIENT_JSON | jq -r '.tags | contains(["modal*"])')" == "false" ]] ; then
                CLIENT="$(echo $CLIENT_JSON | jq -r ".address")"
                hyprctl -q dispatch movetoworkspacesilent "special:minimized$WSID,address:$CLIENT"
            fi
        done <<< "$(hyprctl clients -j | jq -cr "map(select(.workspace.id == $WSID and .floating == true)) | .[]" 2>/dev/null)"

        hyprctl -q dispatch focuswindow "address:${1:20:12}"
    elif [[ "$JSON" == "{}" ]] ; then
        WSID="$(hyprctl activeworkspace -j | jq -r '.id')"

        while IFS= read -r CLIENT ; do
            hyprctl -q dispatch movetoworkspacesilent "$WSID,address:$CLIENT"
        done <<< "$(hyprctl clients -j | jq -cr ".[] | select(.workspace.name == \"special:minimized$WSID\")" | jq -r '.address')"

        hyprctl -q dispatch cyclenext next floating
        hyprctl -q dispatch alterzorder "top,address$(hyprctl activewindow -j | jq -r ".address")"
    fi
  fi
}

SOCKET2_PATH="$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock"

nc -U "$SOCKET2_PATH" | while read -r line; do handle "$line"; done

