#!/bin/bash
ACTIVE_WINDOW_JSON="$(hyprctl activewindow -j)"
FLOATING_STATUS="$(echo "$ACTIVE_WINDOW_JSON" | jq -r '.floating')"

if [ "$FLOATING_STATUS" = "true" ]; then
    hyprctl dispatch cyclenext next tiled
else
    WORKSPACE_ID="$(hyprctl activeworkspace -j | jq -r '.id')"
    CLIENTS_JSON="$(hyprctl clients -j)"

    echo $CLIENTS_JSON | \
    jq -r "map(select(.workspace.name == \"special:minimized$WORKSPACE_ID\")) | .[].address" | \
    xargs -I{} hyprctl dispatch movetoworkspacesilent $WORKSPACE_ID,address:{}

    hyprctl dispatch cyclenext next floating
fi
